import React from 'react';

const PolicyContents = ({ activeTab }) => {
  return (
    <>
      {/* TERMS & CONDITIONS */}
      {activeTab === 'terms' && (
        <div className="space-y-6 text-sm text-slate-600 dark:text-slate-300 leading-relaxed animate-fadeIn">
          <div className="border-b border-slate-100 dark:border-slate-800 pb-4">
            <h1 className="text-2xl font-extrabold text-slate-900 dark:text-white">Terms & Conditions</h1>
            <p className="text-xs text-slate-400 mt-1">Updated at 2024-08-26</p>
          </div>

          <div className="space-y-4">
            <h3 className="font-bold text-slate-900 dark:text-white text-base">General Terms</h3>
            <p>
              By accessing and placing an order with Likesszon Store, you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and Likesszon Store.
            </p>
            <p>
              Under no circumstances shall Likesszon Store team be liable for any direct, indirect, special, incidental, or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if Likesszon Store team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair, or correction of equipment or data, you assume any costs thereof.
            </p>
            <p>
              Likesszon Store will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the right to change prices and revise the resources usage policy at any moment without any prior intimation / notice.
            </p>
          </div>

          <div className="space-y-4">
            <h3 className="font-bold text-slate-900 dark:text-white text-base">License</h3>
            <p>
              Likesszon Store grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website strictly in accordance with the terms of this Agreement.
            </p>
            <p>
              These Terms & Conditions are a contract between you and Likesszon Store (referred to in these Terms & Conditions as "Likesszon Store", "us", "we" or "our"), the provider of the Likesszon Store website and the services accessible from the Likesszon Store website.
            </p>
          </div>

          <div className="space-y-4">
            <h3 className="font-bold text-slate-900 dark:text-white text-base">Definitions and Key Terms</h3>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you.</li>
              <li><strong>Company:</strong> refers to Likesszon Store, that is responsible for your information.</li>
              <li><strong>Country:</strong> where Likesszon Store is based, in this case is India.</li>
              <li><strong>Website:</strong> Likesszon Store’s site, which can be accessed via: <a href="https://www.likesszon.in" target="_blank" rel="noreferrer" className="text-indigo-600 hover:underline">https://www.likesszon.in</a></li>
            </ul>
          </div>

          <div className="space-y-4">
            <h3 className="font-bold text-slate-900 dark:text-white text-base">Restrictions</h3>
            <p>You agree not to, and you will not permit others to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>License, sell, rent, lease, assign, distribute, or otherwise commercially exploit the website.</li>
              <li>Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the website.</li>
              <li>Remove, alter or obscure any proprietary notice of Likesszon Store or its affiliates.</li>
            </ul>
          </div>

          <div className="space-y-4">
            <h3 className="font-bold text-slate-900 dark:text-white text-base">Intellectual Property</h3>
            <p>
              The Website and its entire contents, features, and functionality are owned by Likesszon Store, its licensors or other providers of such material and are protected by India and international copyright, trademark, and other intellectual property laws.
            </p>
          </div>

          <div className="space-y-4">
            <h3 className="font-bold text-slate-900 dark:text-white text-base">Choice of Law and Venue</h3>
            <p>
              The Terms of Use and policies shall be expounded and construed with and by the laws of India. Disputes of any sort will be subject to the exclusive jurisdiction of the courts situated within New Delhi and the user hereby will have to comply with the jurisdiction of the courts of Delhi.
            </p>
          </div>

          <div className="space-y-4">
            <h3 className="font-bold text-slate-900 dark:text-white text-base">Contact Us</h3>
            <p>Don't hesitate to contact us if you have any questions.</p>
            <ul className="space-y-1 font-semibold text-slate-800 dark:text-slate-200">
              <li>Via Email: likevideoproduction@gmail.com</li>
              <li>Via Phone Number: 9304264241</li>
            </ul>
          </div>
        </div>
      )}

      {/* RETURN & REFUND POLICY */}
      {activeTab === 'returns' && (
        <div className="space-y-6 text-sm text-slate-600 dark:text-slate-300 leading-relaxed animate-fadeIn">
          <div className="border-b border-slate-100 dark:border-slate-800 pb-4">
            <h1 className="text-2xl font-extrabold text-slate-905 dark:text-white">Return & Refund Policy</h1>
            <p className="text-xs text-slate-400 mt-1">Updated at 2025-09-04</p>
          </div>

          <div className="space-y-4">
            <p>
              If you are not happy with your purchase, we will accept a return of an unused product within <strong>3 days</strong> from the date of delivery of the products.
            </p>
            <p>
              Once we receive the returned item Mobile & Electronics will then give a full refund (excluding shipping as we are unable to refund the initial shipping cost of your order) post verification of the product at our warehouse. Refund shall be processed as per the applicable guidelines / notification / law passed by RBI from time to time and it may take <strong>07-14 days</strong> additional business days to reflect the same in your account.
            </p>
          </div>

          <div className="rounded-xl bg-indigo-50 dark:bg-indigo-950/20 border border-indigo-100 dark:border-indigo-900/50 p-4 space-y-2">
            <h3 className="font-bold text-slate-900 dark:text-white text-sm">🛡️ Warranty & Return Rules Summary</h3>
            <p className="text-xs leading-relaxed text-slate-600 dark:text-slate-350">
              <strong>Standard policy:</strong> Damage, Missing, Not Working items qualify for a Full Refund if reported within <strong>7 days</strong> after delivery. No returns or exchanges are accepted after this period.
            </p>
            <p className="text-xs leading-relaxed text-slate-600 dark:text-slate-350">
              <strong>Brand Warranty:</strong> Different brands in our store carry their own warranty and guarantee periods. You will find brand-specific warranty information in the description box of each individual product item.
            </p>
          </div>
        </div>
      )}

      {/* PRIVACY POLICY */}
      {activeTab === 'privacy' && (
        <div className="space-y-6 text-sm text-slate-600 dark:text-slate-300 leading-relaxed animate-fadeIn">
          <div className="border-b border-slate-100 dark:border-slate-800 pb-4">
            <h1 className="text-2xl font-extrabold text-slate-905 dark:text-white">Privacy Policy</h1>
            <p className="text-xs text-slate-400 mt-1">Updated at 2024-08-26</p>
          </div>

          <div className="space-y-4">
            <p>
              We take security and privacy with the utmost regard. By visiting this Website you agree to be bound by the terms and conditions of this Privacy Policy. If you do not agree please do not use or access our Website.
            </p>
            <p>
              By use of the Website, you expressly consent to our use and disclosure of your personal information in accordance with this Privacy Policy. Our privacy policy is subject to change at any time without notice.
            </p>
          </div>

          <div className="space-y-4">
            <h3 className="font-bold text-slate-900 dark:text-white text-base">Information Collection</h3>
            <p>
              We collect information to enable us to provide a safe, personalized, and optimized experience to our users. You can browse the website anonymously without revealing your identity. Once you register for an account, we collect personally identifiable information such as your name, phone number, email address, and credit card/payment instrument details.
            </p>
            <p>
              We collect buying behavior data when you buy products on our website. We also retain correspondence or message board posts as necessary to resolve disputes, provide support and troubleshoot problems.
            </p>
          </div>

          <div className="space-y-4">
            <h3 className="font-bold text-slate-900 dark:text-white text-base">Cookies</h3>
            <p>
              We use cookies to analyze webpage flow and measure promotional effectiveness. Cookies allow you to enter passwords less frequently. Most browsers let you block cookies; however, doing so may limit certain site functionalities.
            </p>
          </div>

          <div className="space-y-4">
            <h3 className="font-bold text-slate-900 dark:text-white text-base">Sharing of Personal Information</h3>
            <p>
              We may share personal information with our other corporate entities and affiliates to help detect and prevent identity theft, fraud, and illegal acts. We may disclose personal information if required to do so by law or in the good faith belief that such disclosure is necessary to respond to court orders or protect the safety of our users or the general public.
            </p>
          </div>

          <div className="space-y-4">
            <h3 className="font-bold text-slate-905 dark:text-white text-base">Grievance Officer</h3>
            <p>In accordance with Information Technology Act 2000, details of the Grievance Officer are:</p>
            <ul className="space-y-1 font-semibold text-slate-800 dark:text-slate-200">
              <li>Name/Address: Likesszon Store, New Area 1st Gali, Okni near Joda shiv temple, Ward 20</li>
              <li>Phone: 9304264241</li>
              <li>Email: likevideoproduction@gmail.com</li>
              <li>Timings: Mon to Fri (9AM to 6PM)</li>
            </ul>
          </div>
        </div>
      )}

      {/* SHIPPING & PAYMENT POLICY */}
      {activeTab === 'shipping' && (
        <div className="space-y-6 text-sm text-slate-600 dark:text-slate-300 leading-relaxed animate-fadeIn">
          <div className="border-b border-slate-100 dark:border-slate-800 pb-4">
            <h1 className="text-2xl font-extrabold text-slate-905 dark:text-white">Shipping & Payment Policy</h1>
            <p className="text-xs text-slate-400 mt-1">Updated at 2024-08-26</p>
          </div>

          <div className="space-y-4">
            <p>
              We endeavour to dispatch all products ordered within <strong>48 hours</strong> after the order has been placed and accepted by us. Likesszon Store insures each order through transit up until it is delivered to you.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-4">
            <div className="border border-slate-100 dark:border-slate-800/80 p-5 rounded-2xl space-y-2 bg-slate-50/50 dark:bg-slate-900/50">
              <h3 className="font-bold text-slate-900 dark:text-white text-sm">🚚 Delivery Details</h3>
              <ul className="space-y-1.5 text-xs text-slate-500">
                <li><strong>Charges:</strong> All domestic orders are delivered for <strong>free of charge</strong>.</li>
                <li><strong>Time:</strong> Deliveries are fulfilled within <strong>4 to 7 Business days</strong> (excludes public holidays).</li>
                <li><strong>Coverage:</strong> We deliver PAN India. Contact support at 9304264241 for inquiry.</li>
              </ul>
            </div>

            <div className="border border-slate-100 dark:border-slate-800/80 p-5 rounded-2xl space-y-2 bg-slate-50/50 dark:bg-slate-900/50">
              <h3 className="font-bold text-slate-900 dark:text-white text-sm">💳 Payments</h3>
              <ul className="space-y-1.5 text-xs text-slate-500">
                <li><strong>Security:</strong> State-of-the-art SSL 256-bit encrypted checkout.</li>
                <li><strong>Methods:</strong> Accepts major credit and debit cards.</li>
                <li><strong>Dispatch:</strong> Orders dispatched within 48 hours of payment verification.</li>
              </ul>
            </div>
          </div>
        </div>
      )}
    </>
  );
};

export default PolicyContents;
